/**
 * User model for Haru_chat
 * Represents a user entity
 * 
 * @module models/User.js
 */

/**
 *  Represents a user of haru_chat
 */
class User {
    /**
     * 
     * @param {?number} id - User id. can be null because the id will be generated by the database .
     * @param {string} username - username of the user.
     * @param {string} password - hashed password of the user.
     * @param {Date} createdAt - Account creation date.
     * @param {boolean} isBanned - Weather the user is banned or not.
     */
    constructor(id, username, password, createdAt, isBanned) {
        if (id !== null && typeof id !== "number") {
            throw new Error("id must be a number");
        }
        this._id = id;

        if (typeof username !== "string" || username.trim() === "") {
            throw new Error("username must be a string and not empty");
        }
        this._username = username;

        if (typeof password !== "string" || password.trim() === "") {
            throw new Error("password can't be empty");
        }
        this._password = password; // this will be hashed before storage

        if (!(createdAt instanceof Date)) {
            throw new Error("createdAt must be a Date object");
        }
        this._createdAt = createdAt;

        if (typeof isBanned !== "boolean") {
            throw new Error("isBanned must be a boolean");
        }
        this._isBanned = isBanned;

        this._roles = [];
    }

    /**
     * 
     * @returns {?number} User ID
     */
    getId() {
        return this._id;
    };

    /**
     * 
     * @param {?number} id 
     */
    setId(id) {
        if (id !== null && typeof id !== "number") {
            throw new Error("id must be a number");
        }
        this._id = id;
    };

    /**
     * 
     * @returns {string} Username
     */
    getUsername() {
        return this._username;
    };

    /**
     * 
     * @param {string} username 
     */
    setUsername(username) {
        if (typeof username !== "string" || username.trim() === "") {
            throw new Error("username must be a string and not empty");
        }
        this._username = username;
    };

    /**
     * Sets password.
     * This should be hashed before storage
     * 
     * @param {string} password 
     */
    setPassword(password) {
        this._password = password;
    };

    /**
     * 
     * @returns {Date} Account creation date
     */
    getCreatedAt() {
        return this._createdAt;
    };

    /**
     * 
     * @returns {boolean} Weather user is banned or not.
     */
    getIsBanned() {
        return this._isBanned;
    };

    /**
     * sets the banned status of a user 
     * 
     * @param {boolean} banned 
     */
    setIsBanned(banned) {
        if (typeof banned !== "boolean") {
            throw new Error("isBanned must be a boolean");
        }
        this._isBanned = banned;
    };

    /**
     * 
     * @returns {string[]} A copy of the user's roles
     */
    getRoles() {
        return[...this._roles];
    };

    /**
     * 
     * @param {string[]} roles Sets the user's roles
     */
    setRoles(roles) {
        if (!Array.isArray(roles)) {
            throw new Error("Error: roles must be of type array");
        }

        this._roles = [...roles];
    };

    /**
     *  Checks if the user has a certain role
     * @param {string} roleName 
     * @returns {boolean}
     */
    hasRole(roleName) {
        return this._roles.includes(roleName);
    };

    /**
     * Adds a role to a user e.g. "user"
     * @param {string} roleName 
     */
    addRole(roleName) {
        if (!this._roles.includes(roleName)) {
            this._roles.push(roleName);
        }
    }

    /**
     * returns true if the user has the admin role
     * @returns {boolean} 
     */
    isAdmin() {
        return this._roles.includes("admin");
    }

    /**
     *  Removes a role from the user
     * @param {string} roleName 
     */
    removeRole(roleName) {
        if (typeof roleName !== "string" || roleName.trim() === "") {
            throw new Error("Error role must be of type string and not empty");
        }

        const index = this._roles.indexOf(roleName);
        if (index !== -1) {
            this._roles.splice(index, 1);
        }
    };

    /**
     * returns a safe, serializable version of the user without the password
     * @returns {{id: number|null, username: string, createdAt: Date, isBanned: boolean, roles: string[]}}
     */
    getSafeObject() {
        return {
            id: this._id,
            username: this._username,
            createdAt: this._createdAt,
            isBanned: this._isBanned,
            roles: this.getRoles()
        };
    };
};

export { User };